config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # root "groups#index"
  authenticated :user do
    root 'groups#index', as: :authenticated_root
  end
  unauthenticated do
    root "welcomes#index"
  end

  resources :groups, only:[:index,:new,:create] do
    resources :payments, only:[:index,:new,:create]
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.present?
      can :manage, :all
    else
      cannot :manage, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/group.rb
class Group < ApplicationRecord
  #  update validations
  belongs_to :author, class_name: 'User'
  has_many :group_payments
  has_many :payments, through: :group_payments
  validates :name, presence: true
  validates :icon, presence: true

  def toal_amount
    payments.sum(:amount)
  end
end

app/models/group_payment.rb
class GroupPayment < ApplicationRecord
  #  update validations
  belongs_to :payment
  belongs_to :group
end

app/models/payment.rb
class Payment < ApplicationRecord
  #  update validations
  belongs_to :author, class_name: 'User'
  has_many :group_payments
  has_many :groups, through: :group_payments
  validates :name, presence: true
  validates :amount, numericality: { greater_than_or_equal_to: 0 }
  validates :amount, numericality: { only_integer: true }
end

app/models/user.rb
class User < ApplicationRecord
  #  update validations
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :groups, foreign_key: 'author_id'
  has_many :payments, foreign_key: 'author_id'
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  # load resources
  before_action :authenticate_user!
  load_and_authorize_resource
  def index
    @groups = current_user.groups.order(created_at: :desc)
  end

  def new
    @group = Group.new
  end

  def create
    @group = current_user.groups.new(group_params)
    if @group.save
      redirect_to groups_path
    else
      render :new
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  # load resources
  before_action :authenticate_user!
  load_and_authorize_resource
  def index
    @group = Group.find(params[:group_id])
    @payments = @group.payments.order(created_at: :desc)
  end

  def new
    @group = Group.find(params[:group_id])
    @expense = @group.payments.new
  end

  def create
    @group = Group.find(params[:group_id])
    @expense = @group.payments.new(expense_params)
    @expense.author = current_user

    if @expense.save
      @group.payments << @expense
      redirect_to group_payments_path(@group), notice: 'Transaction was successfully created.'
    else
      flash[:alert] = 'Transaction could not be created.'
      render :new
    end
  end

  private

  def expense_params
    params.require(:expense).permit(:name, :amount)
  end
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  # load resources
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/index.html.erb
<div class='container'>
<div class='header'>
<h1>CATEGORIES</h1>
</div>
<div class='cat-container'>
<% @groups.each do |group| %>
 <%= link_to group_payments_path(group) do %>
<div class='category'  >
  <%= image_tag(group.icon, alt: 'Icon') %>
  <div class='products'>
<h2><%=group.name%></h2>
<p><%=group.created_at.to_date%></p>
</div>
<p>$<%=group.toal_amount%></p>
</div>
<%end%>
<%end%>
</div>
</div>
<div class='btn-div'>
<%=link_to 'Add New Category',new_group_path,class:'category-btn'%>
</div>

app/views/groups/new.html.erb
<section>
<header class='form-header'>
<%= link_to root_path do %>
  <%= image_tag "back_arrow.svg" %>
<% end %>
<h2>Create New Category</h2>
</header>
<div class='form-container'>
<%= form_with model: @group, url: groups_path, method: :post, local: true, scope: :group do |f| %>
<div class='form'>
  <div class='field'>
  <%= f.label :name %><br>
  <%= f.text_field :name, required: true,placeholder:'enter a name' %>
</div>
<div class='field'>
<%= f.label :icon %><br>
 <%= f.select :icon, options_for_select([
        ['Select an icon', ''],
        ['Shopping', 'shopping.png'],
        ['Grocery', 'grocery.png']
      ], selected: @group.icon), {}, class: 'field-select' %>
</div>
<div class='submit-button'>
<%= f.submit "Create category",class:'catt-btn' %>
</div>
</div>
<% end %>
</div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

       <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@200;300;700;800&family=Pacifico&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/payments/index.html.erb
<div class= 'container'>
<div class='form-header'>
<%= link_to root_path do %>
  <%= image_tag "back_arrow.svg" %>
<% end %>
<p>total amount:    $<%=@group.toal_amount%></p>
</div>
<h1 class='transact'>Transactions</h1>
<div class='cat-container'>
<%@payments.each do |transaction|%>
<div class='category'>
<p><%=transaction.name%></p>
<p>$<%=transaction.amount%></p>
</div>
<%end%>
</div>
<%= link_to 'Add new transaction',new_group_payment_path(@group),class:'catt-btn'%>
</div>

app/views/payments/new.html.erb
<section>
<header class='form-header'>
<%= link_to group_payments_path(@group) do %>
  <%= image_tag "back_arrow.svg" %>
<% end %>
<h2>Create New Transactions</h2>
</header>
<div class='form-container'>
<%= form_with model: @expense, url: group_payments_path(@group), method: :post, local: true, scope: :expense do |f| %>
<div class='form'>
  <div class='field'>
  <%= f.label :name %><br>
  <%= f.text_field :name, required: true,placeholder:'enter a name' %>
</div>
<div class='field'>
 <%= f.label :amount %><br>
  <%= f.number_field :amount, required: true %>
</div>
<div class="submit-button">
<%= f.submit "Save transaction" ,class:'catt-btn'%>
</div>
</div>
<% end %>
</div>
</section>

app/views/welcomes/index.html.erb
<div class='welcome-page'>
<h1>Budget app</h1>
<div class='login-btns'>
<%= link_to 'LOGIN',user_session_path,class:'login' %>
<%= link_to 'SIGN UP',new_user_registration_path,class:'sign-up' %>
</div>
</div>